name: Build, Release & Publish
on: push

jobs:
  build:
    name: Checkout & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      #
      # ADD TEST/BUILD STEPS HERE
      #

  release:
    name: Check version & Create release
    runs-on: ubuntu-latest
    needs: build
    outputs:
      released: ${{ steps.check.outputs.version }} # expose release.outputs.released for the "publish" job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: EndBug/version-check@v2
      id: check
      with:
        file-name: haxelib.json
        diff-search: true
    - name: Create Release
      if: steps.check.outputs.changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.check.outputs.version }}
        name: ${{ steps.check.outputs.version }}
        draft: false
        prerelease: false

  publish:
    name: Publish to Haxelib
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.2
      - run: |
          haxe -version
          haxelib --debug submit . "$HAXELIB_PASSWORD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAXELIB_PASSWORD: ${{ secrets.HAXELIB_PASSWORD }}
